apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp-dev
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      name: node
      namespace: dev
      jsonPointers:
        - /spec/strategy/canary/steps/1/analysis/templates/0/args
        - /spec/strategy/canary/steps/4/analysis/templates/0/args
  source:
    repoURL: https://github.com/sajilpb/Helm.git
    targetRevision: main
    path: charts/nodeapp
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
